<?php
require "../config.php";
require "../common.php";

// Function to check if an index exists
function indexExists($connection, $tableName, $indexName) {
    $sql = "SHOW INDEX FROM $tableName WHERE Key_name = ?";
    $stmt = $connection->prepare($sql);
    $stmt->execute([$indexName]);
    return $stmt->rowCount() > 0;
}

// Create indexes on specific attributes (e.g., driverName and vehicleType)
try {
    $connection = new PDO($dsn, $username, $password, $options);
    $connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Create an index on the driverName column in the driver table if it doesn't exist
    $indexName = "idx_driverName";
    if (!indexExists($connection, "driver", $indexName)) {
        $indexSql = "CREATE INDEX $indexName ON driver(driverName)";
        $connection->exec($indexSql);
    }

    // Create an index on the vehicleType column in the trip table if it doesn't exist
    $indexName = "idx_vehicleType";
    if (!indexExists($connection, "trip", $indexName)) {
        $indexSql = "CREATE INDEX $indexName ON trip(vehicleType)";
        $connection->exec($indexSql);
    }

    // Repeat this process for other attributes you want to index.

} catch (PDOException $error) {
    echo $error->getMessage();
}

$driverSelectOptions = "";

try {
    $connection = new PDO($dsn, $username, $password, $options);
    $connection->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Fetch the available drivers
    $sql = "SELECT * FROM driver";
    $result = $connection->query($sql);

    if ($result->rowCount() > 0) {
        foreach ($result as $row) {
            $driverID = $row["driverID"];
            $driverName = $row["driverName"];
            $driverSelectOptions .= "<option value='$driverID'>$driverName</option>";
        }
    } else {
        $driverSelectOptions = "<option value='0'>No drivers available</option>";
    }
} catch (PDOException $error) {
    echo $sql . "<br>" . $error->getMessage();
}

if (isset($_POST['submit'])) {
    if (!hash_equals($_SESSION['csrf'], $_POST['csrf'])) {
        die("CSRF token mismatch");
    }

    try {
        $connection->beginTransaction();

        $new_trip = [
            "startlocation" => $_POST['startlocation'],
            "endlocation" => $_POST['endlocation'],
            "noOfTripDays" => $_POST['noOfTripDays'],
            "vehicleType" => $_POST['vehicleType'],
            "Date" => $_POST['Date'],
        ];

        $sql = sprintf(
            "INSERT INTO %s (%s) VALUES (%s)",
            "trip",
            implode(", ", array_keys($new_trip)),
            ":" . implode(", :", array_keys($new_trip))
        );

        $statement = $connection->prepare($sql);
        $statement->execute($new_trip);

        // The tripNo is automatically generated by the database

        if (!empty($_POST["selected_driver"])) {
            $tripNo = $connection->lastInsertId(); // Get the auto-generated tripNo
            foreach ($_POST["selected_driver"] as $driverID) {
                $sql = "INSERT INTO trip_driver (tripNo, driverID) VALUES (:tripNo, :driverID)";
                $stmt = $connection->prepare($sql);
                $stmt->execute([':tripNo' => $tripNo, ':driverID' => $driverID]);
            }
        }

        $connection->commit(); // Commit the transaction
        echo "Trip successfully added.";
    } catch (PDOException $error) {
        $connection->rollBack(); // Roll back the transaction if an error occurred
        echo "Error: " . $error->getMessage();
    }
}
?>

<?php require "templates/header.php"; ?>

<?php if (isset($_POST['submit'])) : ?>
    <blockquote>Trip successfully added.</blockquote>
<?php endif; ?>

<h2>Add a Trip</h2>

<form method="post">
    <input name="csrf" type="hidden" value="<?php echo escape($_SESSION['csrf']); ?>">
    <label for="startlocation">Start Location</label>
    <input type="text" name="startlocation" id="startlocation">
    <label for="endlocation">End Location</label>
    <input type="text" name="endlocation" id="endlocation">
    <label for="noOfTripDays">Number of Trip Days</label>
    <input type="text" name="noOfTripDays" id="noOfTripDays">
    <label for="vehicleType">Vehicle Type</label>
    <input type="text" name="vehicleType" id="vehicleType">
    <label for="Date">Date</label>
    <input type="Date" name="Date" id="Date">

    <label for="selected_driver">Select driver for trip (Hold Ctrl/Cmd to select multiple drivers)</label>
    <select multiple name="selected_driver[]" id="selected_driver">
        <?php echo $driverSelectOptions; ?>
    </select>
    <input type="submit" name="submit" value="Submit">
</form>

<a href="trip_driver.php"><strong>Drivers for Trip</strong></a><br>
<a href="trip.php"><strong>Back to Trip Home</strong></a><br>
<a href="index.php"><strong>Back to Home</strong></a>

<?php require "templates/footer.php"; ?>
